Repository x0lg0n/Boutique-To-Box, pull requests merged in 2025-08, with the labels that each got.

#19 feat: Implement Google OAuth authentication & enhance Design page UI
  .env.example
  DESIGN_PAGE_ENHANCEMENTS.md
  GOOGLE_OAUTH_SETUP_GUIDE.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/GoogleSignInButton.tsx
  src/contexts/AuthContext.tsx
  src/index.css
  src/pages/Design.tsx
  src/pages/GoogleCallback.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/services/googleAuth.ts
  src/vite-env.d.ts
  test.txt
Labels: enhancement, GSSoC '25, frontend, Level 1 - Easy

#22 Added MIT License badge with clickable link in README
  README.md
Labels: documentation, good first issue, GSSoC '25, Level 0 - Beginner

#26 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, GSSoC '25

#23 Update README.md
  README.md
Labels: documentation, good first issue, GSSoC '25, Level 0 - Beginner
